# Generated by Django 5.2.6 on 2026-08-31 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('broadcast', 'Broadcast'), ('event', 'Event')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('via_site', models.BooleanField(default=True)),
                ('via_bot', models.BooleanField(default=False)),
                ('via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.staff')),
                ('target_user', models.ForeignKey(blank=True, help_text='null = broadcast', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('site', 'Site'), ('bot', 'Bot'), ('email', 'Email')], max_length=6)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='sent', max_length=6)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_delivery',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['user', 'channel', 'status'], name='notificatio_user_id_7bc41c_idx')],
            },
        ),
    ]
