# Generated by Django 5.2.6 on 2026-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('broadcast', 'Broadcast'), ('event', 'Event'), ('order_confirmed', 'Order confirmed'), ('service_ready', 'Service ready'), ('volume_warning', 'Volume warning'), ('expiry_warning', 'Expiry warning'), ('admin_broadcast', 'Admin broadcast')], max_length=20),
        ),
    ]
