# Generated by Django 5.2.6 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0, help_text='bytes')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=8)),
                ('sent_to_telegram', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'backup_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('site', 'Site'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('celery_worker', 'Celery worker'), ('celery_beat', 'Celery beat'), ('bot_sales', 'Sales bot'), ('bot_backup', 'Backup bot'), ('panel', 'Panel'), ('mail', 'Mail')], db_index=True, max_length=16)),
                ('is_up', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'health_check',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.CreateModel(
            name='ResourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('net_in', models.BigIntegerField(default=0)),
                ('net_out', models.BigIntegerField(default=0)),
                ('bandwidth_used', models.BigIntegerField(default=0)),
                ('sampled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'resource_stat',
                'ordering': ('-sampled_at',),
            },
        ),
    ]
