# Generated by Django 5.2.6 on 2026-09-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        ('panel', '0004_service_panel_username_per_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='panel.panel'),
        ),
    ]
