# Generated by Django 5.2.6 on 2026-09-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_healthcheck_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcestat',
            name='swap_percent',
            field=models.FloatField(default=0),
        ),
    ]
