# Generated by Django 5.2.6 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('desc_fa', models.TextField(blank=True)),
                ('desc_en', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('custom_volume', 'Custom volume')], default='fixed', max_length=13)),
                ('data_limit', models.BigIntegerField(blank=True, help_text='bytes; null = unlimited', null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='null = timeless', null=True)),
                ('device_limit', models.IntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='tomans', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_gb', models.IntegerField(blank=True, null=True)),
                ('max_gb', models.IntegerField(blank=True, null=True)),
                ('price_per_gb', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
