# Generated by Django 5.2.6 on 2026-09-01 00:38

import apps.panel.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='group_ids',
            field=models.JSONField(blank=True, default=apps.panel.constants.default_group_ids, help_text="panel group ids for this plan; empty = use the panel's default set"),
        ),
    ]
