# Generated by Django 5.2.6 on 2026-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_panel_and_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='group_ids',
            field=models.JSONField(blank=True, default=list, help_text="panel group ids for this plan (from its own panel); empty = the panel's default set"),
        ),
    ]
