# Generated by Django 5.2.6 on 2026-09-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_plan_group_ids_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='carry_over_data',
            field=models.CharField(blank=True, choices=[('both', 'Time + volume'), ('time_only', 'Time only'), ('volume_only', 'Volume only')], help_text='only meaningful when renewal_mode=carry_over', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='renewal_mode',
            field=models.CharField(choices=[('reset', 'Reset (mode A)'), ('carry_over', 'Carry over (mode B)')], default='reset', max_length=10),
        ),
    ]
