# Generated by Django 5.2.6 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_fa', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('body_fa', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('bool', 'Boolean'), ('json', 'JSON')], default='str', max_length=4)),
            ],
            options={
                'db_table': 'setting',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_fa', models.CharField(default='کسپین تانل', max_length=120)),
                ('site_name_en', models.CharField(default='caspintunel', max_length=120)),
                ('site_domain', models.CharField(default='caspin.skin', max_length=120)),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('bot_description_fa', models.TextField(blank=True)),
                ('bot_description_en', models.TextField(blank=True)),
                ('support_telegram', models.CharField(blank=True, max_length=64)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site config',
                'verbose_name_plural': 'site config',
                'db_table': 'site_config',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('palette', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'theme',
                'ordering': ('name',),
            },
        ),
    ]
