# Generated by Django 5.2.6 on 2026-09-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_domain',
            field=models.CharField(default='aicaspin.ir', max_length=120),
        ),
    ]
