# Generated by Django 5.2.6 on 2026-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0009_caspian_light_warning_contrast"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android SMS bridge app"),
                            ("ios", "iPhone shortcut"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="apps/")),
                ("version", models.CharField(blank=True, max_length=40)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="optional external link (e.g. the iCloud shortcut link)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="release notes / extra instructions shown to admins",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "db_table": "app_release",
                "ordering": ("platform",),
            },
        ),
    ]
