# Generated by Django 5.2.6 on 2026-09-25 16:29

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_latin_digits_in_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='starttls', max_length=10)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', apps.common.fields.EncryptedTextField(blank=True, help_text='stored encrypted at rest; never returned by the API')),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_source', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'email settings',
                'db_table': 'email_settings',
            },
        ),
    ]
