# Generated by Django 5.2.6 on 2026-08-31 23:38

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('admin_username', models.CharField(max_length=150)),
                ('admin_password_enc', apps.common.fields.EncryptedTextField(help_text='stored encrypted at rest')),
                ('token_cache', apps.common.fields.EncryptedTextField(blank=True, help_text='cached API token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'panel',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel_username', models.CharField(max_length=64, unique=True)),
                ('subscription_url', models.CharField(blank=True, help_text='fixed — used for QR', max_length=500)),
                ('status', models.CharField(choices=[('on_hold', 'On-Hold'), ('active', 'Active'), ('expired', 'Expired'), ('limited', 'Limited'), ('disabled', 'Disabled'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('expire_strategy', models.CharField(choices=[('fixed_date', 'Fixed date'), ('on_hold', 'On-Hold (start on first connection)'), ('never', 'Never (timeless)')], default='on_hold', max_length=12)),
                ('data_limit', models.BigIntegerField(default=0, help_text='bytes; 0 = unlimited')),
                ('data_used', models.BigIntegerField(default=0, help_text='bytes; cached from panel')),
                ('expire_at', models.DateTimeField(blank=True, help_text='null = timeless', null=True)),
                ('on_hold_duration', models.IntegerField(blank=True, help_text='seconds applied after first connection', null=True)),
                ('on_hold_timeout', models.DateTimeField(blank=True, help_text='deadline for the first connection', null=True)),
                ('online_at', models.DateTimeField(blank=True, help_text='last seen online (synced)', null=True)),
                ('device_limit', models.IntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('source', models.CharField(default='site', max_length=8)),
                ('alert_vol_sent', models.BooleanField(default=False)),
                ('alert_exp_sent', models.BooleanField(default=False)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='plans.plan')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='panel.panel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service',
                'ordering': ('-created_at',),
            },
        ),
    ]
