# Generated by Django 5.2.6 on 2026-09-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='default_group_ids',
            field=models.JSONField(blank=True, default=list, help_text='PasarGuard group id list, e.g. [1, 2]'),
        ),
        migrations.AddField(
            model_name='panel',
            name='subscription_base_url',
            field=models.CharField(blank=True, help_text='optional; prepended when the API returns a relative subscription_url', max_length=255),
        ),
        migrations.AddField(
            model_name='panel',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='last successful panel sync', null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='base_url',
            field=models.URLField(help_text='e.g. https://pas.hunaex.shop'),
        ),
    ]
