# Generated by Django 5.2.6 on 2026-09-01 00:38

import apps.panel.constants
from apps.panel.constants import ALL_PANEL_GROUP_IDS
from django.db import migrations, models


def backfill_default_group_ids(apps, schema_editor):
    Panel = apps.get_model("panel", "Panel")
    for panel in Panel.objects.all():
        if not panel.default_group_ids:
            panel.default_group_ids = list(ALL_PANEL_GROUP_IDS)
            panel.save(update_fields=["default_group_ids"])


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panel_pasarguard_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='default_group_ids',
            field=models.JSONField(blank=True, default=apps.panel.constants.default_group_ids, help_text='fallback PasarGuard group id list, e.g. [5, 6, 8, 10]'),
        ),
        migrations.RunPython(backfill_default_group_ids, migrations.RunPython.noop),
    ]
