# Generated by Django 5.2.6 on 2026-08-31 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new', 'New service'), ('renew', 'Renew'), ('addon_volume', 'Add-on volume')], default='new', max_length=12)),
                ('requested_account_name', models.CharField(blank=True, max_length=64, null=True)),
                ('custom_volume_gb', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=0, help_text='base amount, tomans', max_digits=12)),
                ('amount_unique', models.DecimalField(decimal_places=0, help_text='amount + unique surcharge (200..1500)', max_digits=12)),
                ('amount_unique_lock', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=12, null=True, unique=True)),
                ('unique_expire_at', models.DateTimeField(help_text='reservation expiry')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending_payment', max_length=16)),
                ('source', models.CharField(default='site', max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='plans.plan')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='panel.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['amount_unique', 'status'], name='order_amount__dc47c3_idx')],
            },
        ),
    ]
