# Generated by Django 5.2.6 on 2026-09-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('expired', 'Reservation expired')], db_index=True, default='pending_payment', max_length=16),
        ),
    ]
