# Generated by Django 5.2.6 on 2026-09-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('panel', '0004_service_panel_username_per_panel'),
        ('plans', '0006_plan_carry_over_data_plan_renewal_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_mode', models.CharField(max_length=10)),
                ('carry_over_data', models.CharField(blank=True, max_length=11, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_renewals', to='orders.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_renewals', to='plans.plan')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_renewal', to='panel.service')),
            ],
            options={
                'db_table': 'scheduled_renewal',
                'ordering': ('-created_at',),
            },
        ),
    ]
