# Generated by Django 5.2.6 on 2026-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_scheduledrenewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('new', 'New service'), ('renew', 'Renew'), ('addon_volume', 'Add-on volume'), ('manual', 'Manual (admin-created)')], default='new', max_length=12),
        ),
    ]
