# Generated by Django 5.2.6 on 2026-09-25 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_type"),
        ("plans", "0006_plan_carry_over_data_plan_renewal_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("new", "New service"),
                    ("renew", "Renew"),
                    ("addon_volume", "Add-on volume"),
                    ("manual", "Manual (admin-created)"),
                    ("imported", "Imported (existing panel account linked)"),
                ],
                default="new",
                max_length=12,
            ),
        ),
    ]
