# Generated by Django 5.2.6 on 2026-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Internal staff-only note; never shown to the user'),
        ),
    ]
