# Generated by Django 5.2.6 on 2026-09-25 01:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_permission(apps, schema_editor):
    """"users.delete": soft-delete a customer (and restore one from the
    deleted-users archive) — separate from users.manage because it disables
    every service of the user on the panels."""
    Permission = apps.get_model("accounts", "Permission")
    Permission.objects.update_or_create(code="users.delete", defaults={"name": "Delete / restore users"})


def remove_permission(apps, schema_editor):
    Permission = apps.get_model("accounts", "Permission")
    Permission.objects.filter(code="users.delete").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_normalize_user_phones"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delete_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_users",
                to="accounts.staff",
            ),
        ),
        migrations.CreateModel(
            name="DeletedUserArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_username", models.CharField(db_index=True, max_length=64)),
                ("original_name", models.CharField(blank=True, max_length=120)),
                (
                    "original_phone",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("original_email", models.CharField(blank=True, max_length=255)),
                ("original_telegram_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "original_telegram_username",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("deleted_by_label", models.CharField(blank=True, max_length=150)),
                ("reason", models.TextField()),
                ("orders_count", models.IntegerField(default=0)),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=0, default=0, max_digits=14),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("restored_by_label", models.CharField(blank=True, max_length=150)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deleted_user_archive",
                "ordering": ("-deleted_at", "-id"),
            },
        ),
        migrations.RunPython(add_permission, remove_permission),
    ]
