# Generated by Django 5.2.6 on 2026-09-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="when the user accepted the terms of service (at sign-up)",
                null=True,
            ),
        ),
    ]
