# Generated by Django 5.2.6 on 2026-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_repair_deleted_user_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRevokedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_revoked_token',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
