# Generated by Django 5.2.6 on 2026-08-31 23:38

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='@username or -100... id', max_length=100)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('member_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'required_channel',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('sales', 'Sales bot'), ('backup', 'Backup bot')], max_length=6, unique=True)),
                ('token', apps.common.fields.EncryptedTextField(blank=True, help_text='stored encrypted at rest')),
                ('proxy_url', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_config',
            },
        ),
        migrations.CreateModel(
            name='TelegramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_member_count', models.IntegerField(default=0)),
                ('overlap_bot_channels', models.IntegerField(default=0)),
                ('sampled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'telegram_stats',
                'ordering': ('-sampled_at',),
            },
        ),
    ]
