# Generated by Django 5.2.6 on 2026-09-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredchannel',
            name='invite_link',
            field=models.URLField(blank=True, help_text='optional; needed for private channels so users get a join button'),
        ),
    ]
