# Generated by Django 5.2.6 on 2026-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_requiredchannel_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredchannel',
            name='bot_is_admin',
            field=models.BooleanField(default=False, help_text='set by the /test action — is the sales bot an admin here?'),
        ),
    ]
