# Generated by Django 5.2.6 on 2026-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_sms', '0002_backfill_payment_bank_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
