server {
  listen 80;
  root /usr/share/nginx/html;
  location /panel/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /panel/index.html;
  }
  location = /panel { return 301 /panel/; }
}
